#ifndef __S2_AADS_OOTBF_INSTALLER_TOOLS_V1_H__
#define __S2_AADS_OOTBF_INSTALLER_TOOLS_V1_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_AADS_OOTBF_Installer_Tools_v1_KNOBLEFT_DIG_INPUT 0
#define __S2_AADS_OOTBF_Installer_Tools_v1_KNOBRIGHT_DIG_INPUT 1
#define __S2_AADS_OOTBF_Installer_Tools_v1_ENTER_DIG_INPUT 2
#define __S2_AADS_OOTBF_Installer_Tools_v1_MENU_DIG_INPUT 3
#define __S2_AADS_OOTBF_Installer_Tools_v1_MORE_DIG_INPUT 4
#define __S2_AADS_OOTBF_Installer_Tools_v1_VOLUMEKNOBLEFT_DIG_INPUT 5
#define __S2_AADS_OOTBF_Installer_Tools_v1_VOLUMEKNOBRIGHT_DIG_INPUT 6
#define __S2_AADS_OOTBF_Installer_Tools_v1_START_DIG_INPUT 7
#define __S2_AADS_OOTBF_Installer_Tools_v1_AAEONLINE_DIG_INPUT 8
#define __S2_AADS_OOTBF_Installer_Tools_v1_CENIPODINUSE_DIG_INPUT 9
#define __S2_AADS_OOTBF_Installer_Tools_v1_AASONLINE_DIG_INPUT 10
#define __S2_AADS_OOTBF_Installer_Tools_v1_REGENERATEROOMLIST_DIG_INPUT 11
#define __S2_AADS_OOTBF_Installer_Tools_v1_REGENERATESOURCELIST_DIG_INPUT 12
#define __S2_AADS_OOTBF_Installer_Tools_v1_AUTODISCMATCHFOUND_DIG_INPUT 13
#define __S2_AADS_OOTBF_Installer_Tools_v1_AUTODISCMATCHNOTFOUND_DIG_INPUT 14
#define __S2_AADS_OOTBF_Installer_Tools_v1_AUTODISCDEVICEPRESSED_DIG_INPUT 15
#define __S2_AADS_OOTBF_Installer_Tools_v1_AUTODISCAASFAILNONEFOUND_DIG_INPUT 16
#define __S2_AADS_OOTBF_Installer_Tools_v1_AUTODISCAASFAILMULTIPLEFOUND_DIG_INPUT 17
#define __S2_AADS_OOTBF_Installer_Tools_v1_AUTODISCDISCOVERYCOMPLETE_DIG_INPUT 18
#define __S2_AADS_OOTBF_Installer_Tools_v1_WRITECONFIG_DIG_INPUT 19
#define __S2_AADS_OOTBF_Installer_Tools_v1_RESTOREDEFAULTSDONE_DIG_INPUT 20
#define __S2_AADS_OOTBF_Installer_Tools_v1_RESTOREAUDIODEFAULTSDONE_DIG_INPUT 21
#define __S2_AADS_OOTBF_Installer_Tools_v1_TSIDDISCOVERYCOMPLETE_DIG_INPUT 22

#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCEDISABLEDFB_DIG_INPUT 23
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCEDISABLEDFB_ARRAY_LENGTH 6

/*
* ANALOG_INPUT
*/
#define __S2_AADS_OOTBF_Installer_Tools_v1_SCROLLPAGESIZE_ANALOG_INPUT 0
#define __S2_AADS_OOTBF_Installer_Tools_v1_CONFIGUREDREQION_ANALOG_INPUT 1
#define __S2_AADS_OOTBF_Installer_Tools_v1_CONFIGUREDNUMBERROOMS_ANALOG_INPUT 2
#define __S2_AADS_OOTBF_Installer_Tools_v1_AUDIOSERVERZONES_ANALOG_INPUT 3
#define __S2_AADS_OOTBF_Installer_Tools_v1_MANUALAUDIOSERVERZONES_ANALOG_INPUT 4
#define __S2_AADS_OOTBF_Installer_Tools_v1_IDDONEFB_ANALOG_INPUT 5
#define __S2_AADS_OOTBF_Installer_Tools_v1_SYSTEMTYPE_ANALOG_INPUT 6

#define __S2_AADS_OOTBF_Installer_Tools_v1_EDITEDTEXT$_STRING_INPUT 7
#define __S2_AADS_OOTBF_Installer_Tools_v1_EDITEDTEXT$_STRING_MAX_LEN 24
CREATE_STRING_STRUCT( S2_AADS_OOTBF_Installer_Tools_v1, __EDITEDTEXT$, __S2_AADS_OOTBF_Installer_Tools_v1_EDITEDTEXT$_STRING_MAX_LEN );


#define __S2_AADS_OOTBF_Installer_Tools_v1_KEYPADMAPIN_ANALOG_INPUT 8
#define __S2_AADS_OOTBF_Installer_Tools_v1_KEYPADMAPIN_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_Installer_Tools_v1_ROOMNAMEIN$_STRING_INPUT 14
#define __S2_AADS_OOTBF_Installer_Tools_v1_ROOMNAMEIN$_ARRAY_NUM_ELEMS 24
#define __S2_AADS_OOTBF_Installer_Tools_v1_ROOMNAMEIN$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __ROOMNAMEIN$, __S2_AADS_OOTBF_Installer_Tools_v1_ROOMNAMEIN$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Installer_Tools_v1_ROOMNAMEIN$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCENAMEIN$_STRING_INPUT 38
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCENAMEIN$_ARRAY_NUM_ELEMS 10
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCENAMEIN$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __SOURCENAMEIN$, __S2_AADS_OOTBF_Installer_Tools_v1_SOURCENAMEIN$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Installer_Tools_v1_SOURCENAMEIN$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_Installer_Tools_v1_ABOUT$_STRING_INPUT 48
#define __S2_AADS_OOTBF_Installer_Tools_v1_ABOUT$_ARRAY_NUM_ELEMS 6
#define __S2_AADS_OOTBF_Installer_Tools_v1_ABOUT$_ARRAY_NUM_CHARS 48
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __ABOUT$, __S2_AADS_OOTBF_Installer_Tools_v1_ABOUT$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Installer_Tools_v1_ABOUT$_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/
#define __S2_AADS_OOTBF_Installer_Tools_v1_EXITINSTALLER_DIG_OUTPUT 0
#define __S2_AADS_OOTBF_Installer_Tools_v1_ENTERBUTTONFB_DIG_OUTPUT 1
#define __S2_AADS_OOTBF_Installer_Tools_v1_TEXTEDITKNOBLEFT_DIG_OUTPUT 2
#define __S2_AADS_OOTBF_Installer_Tools_v1_TEXTEDITKNOBRIGHT_DIG_OUTPUT 3
#define __S2_AADS_OOTBF_Installer_Tools_v1_TEXTEDITENTER_DIG_OUTPUT 4
#define __S2_AADS_OOTBF_Installer_Tools_v1_TEXTEDITVOLUMEKNOBLEFT_DIG_OUTPUT 5
#define __S2_AADS_OOTBF_Installer_Tools_v1_TEXTEDITVOLUMEKNOBRIGHT_DIG_OUTPUT 6
#define __S2_AADS_OOTBF_Installer_Tools_v1_TSIDINIT_DIG_OUTPUT 7
#define __S2_AADS_OOTBF_Installer_Tools_v1_TSIDSTART_DIG_OUTPUT 8
#define __S2_AADS_OOTBF_Installer_Tools_v1_TSIDSETONEID_DIG_OUTPUT 9
#define __S2_AADS_OOTBF_Installer_Tools_v1_TSIDSTOPCONFIG_DIG_OUTPUT 10
#define __S2_AADS_OOTBF_Installer_Tools_v1_AUTODISCDISCOVER_DIG_OUTPUT 11
#define __S2_AADS_OOTBF_Installer_Tools_v1_AUTODISCABORT_DIG_OUTPUT 12
#define __S2_AADS_OOTBF_Installer_Tools_v1_SETAAEID_DIG_OUTPUT 13
#define __S2_AADS_OOTBF_Installer_Tools_v1_IPODADDED_DIG_OUTPUT 14
#define __S2_AADS_OOTBF_Installer_Tools_v1_IPODREMOVED_DIG_OUTPUT 15
#define __S2_AADS_OOTBF_Installer_Tools_v1_SETIPOD_DIG_OUTPUT 16
#define __S2_AADS_OOTBF_Installer_Tools_v1_AASADDED_DIG_OUTPUT 17
#define __S2_AADS_OOTBF_Installer_Tools_v1_AASREMOVED_DIG_OUTPUT 18
#define __S2_AADS_OOTBF_Installer_Tools_v1_SETAAS_DIG_OUTPUT 19
#define __S2_AADS_OOTBF_Installer_Tools_v1_RESTOREDEFAULTS_DIG_OUTPUT 20
#define __S2_AADS_OOTBF_Installer_Tools_v1_RESTOREAUDIODEFAULTS_DIG_OUTPUT 21

#define __S2_AADS_OOTBF_Installer_Tools_v1_FIELDTOEDIT_DIG_OUTPUT 22
#define __S2_AADS_OOTBF_Installer_Tools_v1_FIELDTOEDIT_ARRAY_LENGTH 3
#define __S2_AADS_OOTBF_Installer_Tools_v1_DIGITALOUT_DIG_OUTPUT 25
#define __S2_AADS_OOTBF_Installer_Tools_v1_DIGITALOUT_ARRAY_LENGTH 4
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCEENABLE_DIG_OUTPUT 29
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCEENABLE_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCEDISABLE_DIG_OUTPUT 35
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCEDISABLE_ARRAY_LENGTH 6

/*
* ANALOG_OUTPUT
*/
#define __S2_AADS_OOTBF_Installer_Tools_v1_CURRENTMENU_ANALOG_OUTPUT 0
#define __S2_AADS_OOTBF_Installer_Tools_v1_NEWREGION_ANALOG_OUTPUT 1
#define __S2_AADS_OOTBF_Installer_Tools_v1_NEWNUMBERROOMS_ANALOG_OUTPUT 2
#define __S2_AADS_OOTBF_Installer_Tools_v1_TSIDTOSET_ANALOG_OUTPUT 3
#define __S2_AADS_OOTBF_Installer_Tools_v1_CENIPODCONFIGURED_ANALOG_OUTPUT 4
#define __S2_AADS_OOTBF_Installer_Tools_v1_AASCONFIGURED_ANALOG_OUTPUT 5
#define __S2_AADS_OOTBF_Installer_Tools_v1_BACKLIGHTCONFIGURED_ANALOG_OUTPUT 6

#define __S2_AADS_OOTBF_Installer_Tools_v1_ROOMLIST$_STRING_OUTPUT 7
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCELIST$_STRING_OUTPUT 8
#define __S2_AADS_OOTBF_Installer_Tools_v1_TSIDTYPE$_STRING_OUTPUT 9
#define __S2_AADS_OOTBF_Installer_Tools_v1_AUTODISCTYPE$_STRING_OUTPUT 10
#define __S2_AADS_OOTBF_Installer_Tools_v1_AUTODISCNEXTID$_STRING_OUTPUT 11
#define __S2_AADS_OOTBF_Installer_Tools_v1_TEXTTOEDIT$_STRING_OUTPUT 12

#define __S2_AADS_OOTBF_Installer_Tools_v1_KEYPADMAPOUT_ANALOG_OUTPUT 13
#define __S2_AADS_OOTBF_Installer_Tools_v1_KEYPADMAPOUT_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_Installer_Tools_v1_ANALOGOUT_ANALOG_OUTPUT 19
#define __S2_AADS_OOTBF_Installer_Tools_v1_ANALOGOUT_ARRAY_LENGTH 5
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCETYPEOUT_ANALOG_OUTPUT 24
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCETYPEOUT_ARRAY_LENGTH 10
#define __S2_AADS_OOTBF_Installer_Tools_v1_ROOMNAMEOUT$_STRING_OUTPUT 34
#define __S2_AADS_OOTBF_Installer_Tools_v1_ROOMNAMEOUT$_ARRAY_LENGTH 12
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCENAMEOUT$_STRING_OUTPUT 46
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCENAMEOUT$_ARRAY_LENGTH 10
#define __S2_AADS_OOTBF_Installer_Tools_v1_SERIALOUT$_STRING_OUTPUT 56
#define __S2_AADS_OOTBF_Installer_Tools_v1_SERIALOUT$_ARRAY_LENGTH 3

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_AADS_OOTBF_Installer_Tools_v1_MENULIST$_ARRAY_NUM_ELEMS 10
#define __S2_AADS_OOTBF_Installer_Tools_v1_MENULIST$_ARRAY_NUM_CHARS 32
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __MENULIST$, __S2_AADS_OOTBF_Installer_Tools_v1_MENULIST$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Installer_Tools_v1_MENULIST$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_Installer_Tools_v1_ABOUTLIST$_ARRAY_NUM_ELEMS 6
#define __S2_AADS_OOTBF_Installer_Tools_v1_ABOUTLIST$_ARRAY_NUM_CHARS 20
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __ABOUTLIST$, __S2_AADS_OOTBF_Installer_Tools_v1_ABOUTLIST$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Installer_Tools_v1_ABOUTLIST$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_Installer_Tools_v1_KEYPADLIST$_ARRAY_NUM_ELEMS 3
#define __S2_AADS_OOTBF_Installer_Tools_v1_KEYPADLIST$_ARRAY_NUM_CHARS 10
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __KEYPADLIST$, __S2_AADS_OOTBF_Installer_Tools_v1_KEYPADLIST$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Installer_Tools_v1_KEYPADLIST$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_Installer_Tools_v1_DEFAULTSLIST$_ARRAY_NUM_ELEMS 3
#define __S2_AADS_OOTBF_Installer_Tools_v1_DEFAULTSLIST$_ARRAY_NUM_CHARS 20
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __DEFAULTSLIST$, __S2_AADS_OOTBF_Installer_Tools_v1_DEFAULTSLIST$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Installer_Tools_v1_DEFAULTSLIST$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_Installer_Tools_v1_ROOMNAMELIST$_ARRAY_NUM_ELEMS 16
#define __S2_AADS_OOTBF_Installer_Tools_v1_ROOMNAMELIST$_ARRAY_NUM_CHARS 16
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __ROOMNAMELIST$, __S2_AADS_OOTBF_Installer_Tools_v1_ROOMNAMELIST$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Installer_Tools_v1_ROOMNAMELIST$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCENAMELIST$_ARRAY_NUM_ELEMS 15
#define __S2_AADS_OOTBF_Installer_Tools_v1_SOURCENAMELIST$_ARRAY_NUM_CHARS 16
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __SOURCENAMELIST$, __S2_AADS_OOTBF_Installer_Tools_v1_SOURCENAMELIST$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Installer_Tools_v1_SOURCENAMELIST$_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_AADS_OOTBF_Installer_Tools_v1 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __SOURCEDISABLEDFB );
   DECLARE_IO_ARRAY( __FIELDTOEDIT );
   DECLARE_IO_ARRAY( __DIGITALOUT );
   DECLARE_IO_ARRAY( __SOURCEENABLE );
   DECLARE_IO_ARRAY( __SOURCEDISABLE );
   DECLARE_IO_ARRAY( __KEYPADMAPIN );
   DECLARE_IO_ARRAY( __KEYPADMAPOUT );
   DECLARE_IO_ARRAY( __ANALOGOUT );
   DECLARE_IO_ARRAY( __SOURCETYPEOUT );
   DECLARE_IO_ARRAY( __ROOMNAMEOUT$ );
   DECLARE_IO_ARRAY( __SOURCENAMEOUT$ );
   DECLARE_IO_ARRAY( __SERIALOUT$ );
   unsigned short __NEWREGIONTEMP;
   unsigned short __TEMPNUMBERROOMS;
   unsigned short __SCROLLINDEX;
   unsigned short __SCROLLHIGHLIGHT;
   unsigned short __SCROLLMAX;
   unsigned short __STARTINDEX;
   unsigned short __ENDINDEX;
   unsigned short __MAXROOMSAVAILABLE;
   unsigned short __OLDSCROLLINDEX;
   unsigned short __OLDSCROLLHIGHLIGHT;
   unsigned short __EDITTEXTCALLINGMENU;
   unsigned short __EDITTEXTSELECTION;
   unsigned short __ROOMBEINGEDITED;
   unsigned short __SOURCEBEINGEDITED;
   unsigned short __BUTTONBEINGEDITED;
   unsigned short __SOURCEINDEX;
   unsigned short __SELECTIONBEINGEDITED;
   unsigned short __IDKEYPADSROOM;
   unsigned short __IDKEYPADSTYPE;
   unsigned short __IDKEYPADSSTEP;
   unsigned short __WAITINGFORIDFB;
   unsigned short __WAITINGFORAAEIDFB;
   unsigned short __NETWORKSTEP;
   unsigned short __RESTOREDEFAULTSSTEP;
   unsigned short __NETWORKDEVICETOBECONFIGURED;
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __MENULIST$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __ABOUTLIST$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __KEYPADLIST$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __DEFAULTSLIST$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __ROOMNAMELIST$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __SOURCENAMELIST$ );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_Installer_Tools_v1, __EDITEDTEXT$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __ROOMNAMEIN$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __SOURCENAMEIN$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Installer_Tools_v1, __ABOUT$ );
};

START_NVRAM_VAR_STRUCT( S2_AADS_OOTBF_Installer_Tools_v1 )
{
};

DEFINE_WAITEVENT( S2_AADS_OOTBF_Installer_Tools_v1, NETWORKWAIT );
DEFINE_WAITEVENT( S2_AADS_OOTBF_Installer_Tools_v1, AASNETWORKWAIT );
DEFINE_WAITEVENT( S2_AADS_OOTBF_Installer_Tools_v1, DISCOVERYWAIT );
DEFINE_WAITEVENT( S2_AADS_OOTBF_Installer_Tools_v1, KEYPADIDWAIT );
DEFINE_WAITEVENT( S2_AADS_OOTBF_Installer_Tools_v1, HIDESOURCEMESSAGEWAIT );
DEFINE_WAITEVENT( S2_AADS_OOTBF_Installer_Tools_v1, TSIDWAIT );
DEFINE_WAITEVENT( S2_AADS_OOTBF_Installer_Tools_v1, RESTOREAUDIODEFAULTSWAIT );
DEFINE_WAITEVENT( S2_AADS_OOTBF_Installer_Tools_v1, RESTOREDEFAULTSWAIT );


#endif //__S2_AADS_OOTBF_INSTALLER_TOOLS_V1_H__

