#ifndef __S2_AADS_OOTBF_ROOM_MODE_V1_H__
#define __S2_AADS_OOTBF_ROOM_MODE_V1_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_AADS_OOTBF_Room_Mode_v1_KNOBRIGHT_DIG_INPUT 0
#define __S2_AADS_OOTBF_Room_Mode_v1_KNOBLEFT_DIG_INPUT 1
#define __S2_AADS_OOTBF_Room_Mode_v1_ENTER_DIG_INPUT 2
#define __S2_AADS_OOTBF_Room_Mode_v1_MENU_DIG_INPUT 3
#define __S2_AADS_OOTBF_Room_Mode_v1_MORE_DIG_INPUT 4
#define __S2_AADS_OOTBF_Room_Mode_v1_ROOMANDMORE_DIG_INPUT 5
#define __S2_AADS_OOTBF_Room_Mode_v1_ROOMMODE_DIG_INPUT 6
#define __S2_AADS_OOTBF_Room_Mode_v1_DISPLAY_DIG_INPUT 7
#define __S2_AADS_OOTBF_Room_Mode_v1_EXITGLOBALVOLUME_DIG_INPUT 8
#define __S2_AADS_OOTBF_Room_Mode_v1_EXITROOMMODE_DIG_INPUT 9

#define __S2_AADS_OOTBF_Room_Mode_v1_SOURCEDISABLED_DIG_INPUT 10
#define __S2_AADS_OOTBF_Room_Mode_v1_SOURCEDISABLED_ARRAY_LENGTH 10
#define __S2_AADS_OOTBF_Room_Mode_v1_ROOMBUTTON_DIG_INPUT 20
#define __S2_AADS_OOTBF_Room_Mode_v1_ROOMBUTTON_ARRAY_LENGTH 24

/*
* ANALOG_INPUT
*/
#define __S2_AADS_OOTBF_Room_Mode_v1_SOURCEACTIVE_ANALOG_INPUT 0
#define __S2_AADS_OOTBF_Room_Mode_v1_MAXROOMS_ANALOG_INPUT 1
#define __S2_AADS_OOTBF_Room_Mode_v1_ROOMSEED_ANALOG_INPUT 2



#define __S2_AADS_OOTBF_Room_Mode_v1_SOURCETYPE_ANALOG_INPUT 3
#define __S2_AADS_OOTBF_Room_Mode_v1_SOURCETYPE_ARRAY_LENGTH 10
#define __S2_AADS_OOTBF_Room_Mode_v1_ROOMSOURCE_ANALOG_INPUT 13
#define __S2_AADS_OOTBF_Room_Mode_v1_ROOMSOURCE_ARRAY_LENGTH 24
#define __S2_AADS_OOTBF_Room_Mode_v1_USERMENUIN_ANALOG_INPUT 37
#define __S2_AADS_OOTBF_Room_Mode_v1_USERMENUIN_ARRAY_LENGTH 4
#define __S2_AADS_OOTBF_Room_Mode_v1_INSTALLERMENUIN_ANALOG_INPUT 41
#define __S2_AADS_OOTBF_Room_Mode_v1_INSTALLERMENUIN_ARRAY_LENGTH 4
#define __S2_AADS_OOTBF_Room_Mode_v1_SOURCENAME$_STRING_INPUT 45
#define __S2_AADS_OOTBF_Room_Mode_v1_SOURCENAME$_ARRAY_NUM_ELEMS 10
#define __S2_AADS_OOTBF_Room_Mode_v1_SOURCENAME$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Room_Mode_v1, __SOURCENAME$, __S2_AADS_OOTBF_Room_Mode_v1_SOURCENAME$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Room_Mode_v1_SOURCENAME$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_Room_Mode_v1_ROOMNAME$_STRING_INPUT 55
#define __S2_AADS_OOTBF_Room_Mode_v1_ROOMNAME$_ARRAY_NUM_ELEMS 24
#define __S2_AADS_OOTBF_Room_Mode_v1_ROOMNAME$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Room_Mode_v1, __ROOMNAME$, __S2_AADS_OOTBF_Room_Mode_v1_ROOMNAME$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Room_Mode_v1_ROOMNAME$_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/
#define __S2_AADS_OOTBF_Room_Mode_v1_ENTERFB_DIG_OUTPUT 0
#define __S2_AADS_OOTBF_Room_Mode_v1_CURRENTROOMON_DIG_OUTPUT 1
#define __S2_AADS_OOTBF_Room_Mode_v1_DISCONNECT_DIG_OUTPUT 2
#define __S2_AADS_OOTBF_Room_Mode_v1_CONNECT_DIG_OUTPUT 3
#define __S2_AADS_OOTBF_Room_Mode_v1_CONNECTNEWSOURCE_DIG_OUTPUT 4


/*
* ANALOG_OUTPUT
*/
#define __S2_AADS_OOTBF_Room_Mode_v1_CURRENTMENU_ANALOG_OUTPUT 0
#define __S2_AADS_OOTBF_Room_Mode_v1_LINE1SCROLLARROW_ANALOG_OUTPUT 1
#define __S2_AADS_OOTBF_Room_Mode_v1_LINE2SCROLLARROW_ANALOG_OUTPUT 2
#define __S2_AADS_OOTBF_Room_Mode_v1_SOURCEOUT_ANALOG_OUTPUT 3
#define __S2_AADS_OOTBF_Room_Mode_v1_SOURCETYPEOUT_ANALOG_OUTPUT 4
#define __S2_AADS_OOTBF_Room_Mode_v1_NOWPLAYINGINDEX_ANALOG_OUTPUT 5
#define __S2_AADS_OOTBF_Room_Mode_v1_ROOMSELECTEDFB_ANALOG_OUTPUT 6
#define __S2_AADS_OOTBF_Room_Mode_v1_USERADJUSTINDEX_ANALOG_OUTPUT 7
#define __S2_AADS_OOTBF_Room_Mode_v1_INSTALLERADJUSTINDEX_ANALOG_OUTPUT 8

#define __S2_AADS_OOTBF_Room_Mode_v1_SOURCENAMEOUT$_STRING_OUTPUT 9
#define __S2_AADS_OOTBF_Room_Mode_v1_LINE1$_STRING_OUTPUT 10
#define __S2_AADS_OOTBF_Room_Mode_v1_LINE2$_STRING_OUTPUT 11

#define __S2_AADS_OOTBF_Room_Mode_v1_NEWROOMSOURCE_ANALOG_OUTPUT 12
#define __S2_AADS_OOTBF_Room_Mode_v1_NEWROOMSOURCE_ARRAY_LENGTH 24

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_AADS_OOTBF_Room_Mode_v1_USERADJUST$_ARRAY_NUM_ELEMS 4
#define __S2_AADS_OOTBF_Room_Mode_v1_USERADJUST$_ARRAY_NUM_CHARS 19
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Room_Mode_v1, __USERADJUST$, __S2_AADS_OOTBF_Room_Mode_v1_USERADJUST$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Room_Mode_v1_USERADJUST$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_Room_Mode_v1_INSTALLERADJUST$_ARRAY_NUM_ELEMS 4
#define __S2_AADS_OOTBF_Room_Mode_v1_INSTALLERADJUST$_ARRAY_NUM_CHARS 19
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Room_Mode_v1, __INSTALLERADJUST$, __S2_AADS_OOTBF_Room_Mode_v1_INSTALLERADJUST$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Room_Mode_v1_INSTALLERADJUST$_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_AADS_OOTBF_Room_Mode_v1 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __SOURCEDISABLED );
   DECLARE_IO_ARRAY( __ROOMBUTTON );
   DECLARE_IO_ARRAY( __SOURCETYPE );
   DECLARE_IO_ARRAY( __ROOMSOURCE );
   DECLARE_IO_ARRAY( __USERMENUIN );
   DECLARE_IO_ARRAY( __INSTALLERMENUIN );
   DECLARE_IO_ARRAY( __NEWROOMSOURCE );
   unsigned short __CURRENTROOM;
   unsigned short __CURRENTSOURCE;
   unsigned short __SUBMENU;
   unsigned short __TEMPSOURCE;
   unsigned short __SCROLLINDEX;
   unsigned short __SCROLLMAX;
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Room_Mode_v1, __USERADJUST$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Room_Mode_v1, __INSTALLERADJUST$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Room_Mode_v1, __SOURCENAME$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Room_Mode_v1, __ROOMNAME$ );
};

START_NVRAM_VAR_STRUCT( S2_AADS_OOTBF_Room_Mode_v1 )
{
};



#endif //__S2_AADS_OOTBF_ROOM_MODE_V1_H__

