#ifndef __S2_AADS_OOTBF_SOURCE_MODE_V1_H__
#define __S2_AADS_OOTBF_SOURCE_MODE_V1_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_AADS_OOTBF_Source_Mode_v1_KNOBRIGHT_DIG_INPUT 0
#define __S2_AADS_OOTBF_Source_Mode_v1_KNOBLEFT_DIG_INPUT 1
#define __S2_AADS_OOTBF_Source_Mode_v1_ENTER_DIG_INPUT 2
#define __S2_AADS_OOTBF_Source_Mode_v1_MENU_DIG_INPUT 3
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCEANDMORE_DIG_INPUT 4
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCEMODE_DIG_INPUT 5

#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCEDISABLED_DIG_INPUT 6
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCEDISABLED_ARRAY_LENGTH 10

/*
* ANALOG_INPUT
*/
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCEACTIVE_ANALOG_INPUT 0



#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCETYPE_ANALOG_INPUT 1
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCETYPE_ARRAY_LENGTH 10
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCEGAIN_ANALOG_INPUT 11
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCEGAIN_ARRAY_LENGTH 10
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCENAME$_STRING_INPUT 21
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCENAME$_ARRAY_NUM_ELEMS 10
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCENAME$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Source_Mode_v1, __SOURCENAME$, __S2_AADS_OOTBF_Source_Mode_v1_SOURCENAME$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Source_Mode_v1_SOURCENAME$_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/
#define __S2_AADS_OOTBF_Source_Mode_v1_ENTERFB_DIG_OUTPUT 0
#define __S2_AADS_OOTBF_Source_Mode_v1_CONNECT_DIG_OUTPUT 1


/*
* ANALOG_OUTPUT
*/
#define __S2_AADS_OOTBF_Source_Mode_v1_CURRENTMENU_ANALOG_OUTPUT 0
#define __S2_AADS_OOTBF_Source_Mode_v1_SCROLLARROW_ANALOG_OUTPUT 1
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCEOUT_ANALOG_OUTPUT 2
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCETYPEOUT_ANALOG_OUTPUT 3
#define __S2_AADS_OOTBF_Source_Mode_v1_NOWPLAYINGINDEX_ANALOG_OUTPUT 4
#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCEGAINTOADJUST_ANALOG_OUTPUT 5

#define __S2_AADS_OOTBF_Source_Mode_v1_SOURCENAMEOUT$_STRING_OUTPUT 6
#define __S2_AADS_OOTBF_Source_Mode_v1_LINE1$_STRING_OUTPUT 7
#define __S2_AADS_OOTBF_Source_Mode_v1_LINE2$_STRING_OUTPUT 8


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_AADS_OOTBF_Source_Mode_v1 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __SOURCEDISABLED );
   DECLARE_IO_ARRAY( __SOURCETYPE );
   DECLARE_IO_ARRAY( __SOURCEGAIN );
   unsigned short __G_IINDEX;
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Source_Mode_v1, __SOURCENAME$ );
};

START_NVRAM_VAR_STRUCT( S2_AADS_OOTBF_Source_Mode_v1 )
{
};



#endif //__S2_AADS_OOTBF_SOURCE_MODE_V1_H__

