#ifndef __S2_AADS_OOTBF_XML_FUNCTIONS_V1_H__
#define __S2_AADS_OOTBF_XML_FUNCTIONS_V1_H__



/*
* STRUCTURE S2_AADS_OOTBF_XML_Functions_v1__ROOM
*/
#define ROOM__S2_AADS_OOTBF_XML_Functions_v1_NAME$_STRING_MAX_LEN 32
#define ROOM__S2_AADS_OOTBF_XML_Functions_v1_ID$_STRING_MAX_LEN 6
START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, ROOM )
{
   CREATE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, ROOM__NAME$, ROOM__S2_AADS_OOTBF_XML_Functions_v1_NAME$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, ROOM__NAME$ );
   CREATE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, ROOM__ID$, ROOM__S2_AADS_OOTBF_XML_Functions_v1_ID$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, ROOM__ID$ );
   unsigned short ROOM__OUTPUT;
   unsigned short ROOM__SWITCHER;
   unsigned short ROOM__BASS;
   unsigned short ROOM__TREBLE;
   unsigned short ROOM__BALANCE;
   unsigned short ROOM__MONO;
   unsigned short ROOM__LOUD;
   unsigned short ROOM__MINVOL;
   unsigned short ROOM__MAXVOL;
   unsigned short ROOM__STARTVOL;
};

/*
* STRUCTURE S2_AADS_OOTBF_XML_Functions_v1__SOURCE
*/
#define SOURCE__S2_AADS_OOTBF_XML_Functions_v1_NAME$_STRING_MAX_LEN 32
#define SOURCE__S2_AADS_OOTBF_XML_Functions_v1_ROOMID$_STRING_MAX_LEN 6
#define SOURCE__S2_AADS_OOTBF_XML_Functions_v1_COMMANDFILE$_STRING_MAX_LEN 50
START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, SOURCE )
{
   CREATE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, SOURCE__NAME$, SOURCE__S2_AADS_OOTBF_XML_Functions_v1_NAME$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, SOURCE__NAME$ );
   CREATE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, SOURCE__ROOMID$, SOURCE__S2_AADS_OOTBF_XML_Functions_v1_ROOMID$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, SOURCE__ROOMID$ );
   CREATE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, SOURCE__COMMANDFILE$, SOURCE__S2_AADS_OOTBF_XML_Functions_v1_COMMANDFILE$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, SOURCE__COMMANDFILE$ );
   unsigned short SOURCE__INPUT;
   unsigned short SOURCE__TYPE;
   unsigned short SOURCE__GAIN;
   unsigned short SOURCE__VISIBLE;
   unsigned short SOURCE__MODELID;
   unsigned short SOURCE__PARENTID;
   unsigned short SOURCE__NETID;
   unsigned short SOURCE__CONTROLENTRYID;
   unsigned short SOURCE__ENABLED;
};

/*
* STRUCTURE S2_AADS_OOTBF_XML_Functions_v1__GROUP
*/
#define GROUP__S2_AADS_OOTBF_XML_Functions_v1_NAME$_STRING_MAX_LEN 32
START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, GROUP )
{
   CREATE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, GROUP__NAME$, GROUP__S2_AADS_OOTBF_XML_Functions_v1_NAME$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, GROUP__NAME$ );
   unsigned short GROUP__ID;
   unsigned short GROUP__SOURCE;
   CREATE_INTARRAY1D( S2_AADS_OOTBF_XML_Functions_v1, GROUP__ROOMS, 24 );;
   DECLARE_INTARRAY( S2_AADS_OOTBF_XML_Functions_v1, GROUP__ROOMS );
};

/*
* STRUCTURE S2_AADS_OOTBF_XML_Functions_v1__DEVICE
*/
START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, DEVICE )
{
   unsigned short DEVICE__ISPRESENT;
   unsigned short DEVICE__INPUTSTARTSAT;
};

/*
* STRUCTURE S2_AADS_OOTBF_XML_Functions_v1__SYSTEM
*/
START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, SYSTEM )
{
   unsigned short SYSTEM__LOCATION;
   unsigned short SYSTEM__NUMROOMS;
   CREATE_INTARRAY1D( S2_AADS_OOTBF_XML_Functions_v1, SYSTEM__KEYMAP, 6 );;
   DECLARE_INTARRAY( S2_AADS_OOTBF_XML_Functions_v1, SYSTEM__KEYMAP );
};

/*
* STRUCTURE S2_AADS_OOTBF_XML_Functions_v1__INTERFACE
*/
#define INTERFACE__S2_AADS_OOTBF_XML_Functions_v1_NAME$_STRING_MAX_LEN 32
START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, INTERFACE )
{
   CREATE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, INTERFACE__NAME$, INTERFACE__S2_AADS_OOTBF_XML_Functions_v1_NAME$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, INTERFACE__NAME$ );
   unsigned short INTERFACE__NETID;
   unsigned short INTERFACE__LIBRARYID;
   unsigned short INTERFACE__OUTPUT;
};


/*
* Constructor and Destructor
*/
int S2_AADS_OOTBF_XML_Functions_v1_ROOM_Constructor ( START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, ROOM ) * me, int nVerbose );
int S2_AADS_OOTBF_XML_Functions_v1_ROOM_Destructor ( START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, ROOM ) * me, int nVerbose );
int S2_AADS_OOTBF_XML_Functions_v1_SOURCE_Constructor ( START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, SOURCE ) * me, int nVerbose );
int S2_AADS_OOTBF_XML_Functions_v1_SOURCE_Destructor ( START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, SOURCE ) * me, int nVerbose );
int S2_AADS_OOTBF_XML_Functions_v1_GROUP_Constructor ( START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, GROUP ) * me, int nVerbose );
int S2_AADS_OOTBF_XML_Functions_v1_GROUP_Destructor ( START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, GROUP ) * me, int nVerbose );
int S2_AADS_OOTBF_XML_Functions_v1_DEVICE_Constructor ( START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, DEVICE ) * me, int nVerbose );
int S2_AADS_OOTBF_XML_Functions_v1_DEVICE_Destructor ( START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, DEVICE ) * me, int nVerbose );
int S2_AADS_OOTBF_XML_Functions_v1_SYSTEM_Constructor ( START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, SYSTEM ) * me, int nVerbose );
int S2_AADS_OOTBF_XML_Functions_v1_SYSTEM_Destructor ( START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, SYSTEM ) * me, int nVerbose );
int S2_AADS_OOTBF_XML_Functions_v1_INTERFACE_Constructor ( START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, INTERFACE ) * me, int nVerbose );
int S2_AADS_OOTBF_XML_Functions_v1_INTERFACE_Destructor ( START_STRUCTURE_DEFINITION( S2_AADS_OOTBF_XML_Functions_v1, INTERFACE ) * me, int nVerbose );

/*
* DIGITAL_INPUT
*/
#define __S2_AADS_OOTBF_XML_Functions_v1_SAVESETTINGS_DIG_INPUT 0
#define __S2_AADS_OOTBF_XML_Functions_v1_STARTUPOOTBF_DIG_INPUT 1
#define __S2_AADS_OOTBF_XML_Functions_v1_STARTUPSYSTEMBUILDER_DIG_INPUT 2
#define __S2_AADS_OOTBF_XML_Functions_v1_STARTUPCUSTOM_DIG_INPUT 3
#define __S2_AADS_OOTBF_XML_Functions_v1_RESTOREDEFAULTS_DIG_INPUT 4
#define __S2_AADS_OOTBF_XML_Functions_v1_RESTOREAUDIODEFAULTS_DIG_INPUT 5

#define __S2_AADS_OOTBF_XML_Functions_v1_APADOFFLINE_DIG_INPUT 6
#define __S2_AADS_OOTBF_XML_Functions_v1_APADOFFLINE_ARRAY_LENGTH 12
#define __S2_AADS_OOTBF_XML_Functions_v1_KEYPADOFFLINE_DIG_INPUT 18
#define __S2_AADS_OOTBF_XML_Functions_v1_KEYPADOFFLINE_ARRAY_LENGTH 12

/*
* ANALOG_INPUT
*/
#define __S2_AADS_OOTBF_XML_Functions_v1_TUNERFORMATIN_ANALOG_INPUT 2
#define __S2_AADS_OOTBF_XML_Functions_v1_NUMBEROFROOMSIN_ANALOG_INPUT 3
#define __S2_AADS_OOTBF_XML_Functions_v1_TUNERTYPEIN_ANALOG_INPUT 4

#define __S2_AADS_OOTBF_XML_Functions_v1_MODELNAME$_STRING_INPUT 0
#define __S2_AADS_OOTBF_XML_Functions_v1_MODELNAME$_STRING_MAX_LEN 64
CREATE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, __MODELNAME$, __S2_AADS_OOTBF_XML_Functions_v1_MODELNAME$_STRING_MAX_LEN );
#define __S2_AADS_OOTBF_XML_Functions_v1_FILENAME$_STRING_INPUT 1
#define __S2_AADS_OOTBF_XML_Functions_v1_FILENAME$_STRING_MAX_LEN 64
CREATE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, __FILENAME$, __S2_AADS_OOTBF_XML_Functions_v1_FILENAME$_STRING_MAX_LEN );


#define __S2_AADS_OOTBF_XML_Functions_v1_KEYPADMAPIN_ANALOG_INPUT 5
#define __S2_AADS_OOTBF_XML_Functions_v1_KEYPADMAPIN_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCEENABLEDIN_ANALOG_INPUT 11
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCEENABLEDIN_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_SLOTID_ANALOG_INPUT 17
#define __S2_AADS_OOTBF_XML_Functions_v1_SLOTID_ARRAY_LENGTH 3
#define __S2_AADS_OOTBF_XML_Functions_v1_INPUTROOMNAME$_STRING_INPUT 20
#define __S2_AADS_OOTBF_XML_Functions_v1_INPUTROOMNAME$_ARRAY_NUM_ELEMS 24
#define __S2_AADS_OOTBF_XML_Functions_v1_INPUTROOMNAME$_ARRAY_NUM_CHARS 32
CREATE_STRING_ARRAY( S2_AADS_OOTBF_XML_Functions_v1, __INPUTROOMNAME$, __S2_AADS_OOTBF_XML_Functions_v1_INPUTROOMNAME$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_XML_Functions_v1_INPUTROOMNAME$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_XML_Functions_v1_INPUTSOURCENAME$_STRING_INPUT 44
#define __S2_AADS_OOTBF_XML_Functions_v1_INPUTSOURCENAME$_ARRAY_NUM_ELEMS 6
#define __S2_AADS_OOTBF_XML_Functions_v1_INPUTSOURCENAME$_ARRAY_NUM_CHARS 32
CREATE_STRING_ARRAY( S2_AADS_OOTBF_XML_Functions_v1, __INPUTSOURCENAME$, __S2_AADS_OOTBF_XML_Functions_v1_INPUTSOURCENAME$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_XML_Functions_v1_INPUTSOURCENAME$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_XML_Functions_v1_INPUTGROUPNAME$_STRING_INPUT 50
#define __S2_AADS_OOTBF_XML_Functions_v1_INPUTGROUPNAME$_ARRAY_NUM_ELEMS 6
#define __S2_AADS_OOTBF_XML_Functions_v1_INPUTGROUPNAME$_ARRAY_NUM_CHARS 32
CREATE_STRING_ARRAY( S2_AADS_OOTBF_XML_Functions_v1, __INPUTGROUPNAME$, __S2_AADS_OOTBF_XML_Functions_v1_INPUTGROUPNAME$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_XML_Functions_v1_INPUTGROUPNAME$_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/
#define __S2_AADS_OOTBF_XML_Functions_v1_FILEREADDONE_DIG_OUTPUT 0
#define __S2_AADS_OOTBF_XML_Functions_v1_RESTOREDEFAULTSDONE_DIG_OUTPUT 1
#define __S2_AADS_OOTBF_XML_Functions_v1_RESTOREAUDIODEFAULTSDONE_DIG_OUTPUT 2
#define __S2_AADS_OOTBF_XML_Functions_v1_SYSTEMBUILDERFILEREADERROR_DIG_OUTPUT 3


/*
* ANALOG_OUTPUT
*/
#define __S2_AADS_OOTBF_XML_Functions_v1_TUNERFORMATOUT_ANALOG_OUTPUT 0
#define __S2_AADS_OOTBF_XML_Functions_v1_NUMBEROFROOMSOUT_ANALOG_OUTPUT 1


#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMBASS_ANALOG_OUTPUT 2
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMBASS_ARRAY_LENGTH 24
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMTREBLE_ANALOG_OUTPUT 26
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMTREBLE_ARRAY_LENGTH 24
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMBALANCE_ANALOG_OUTPUT 50
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMBALANCE_ARRAY_LENGTH 24
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMMONO_ANALOG_OUTPUT 74
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMMONO_ARRAY_LENGTH 24
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMLOUDNESS_ANALOG_OUTPUT 98
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMLOUDNESS_ARRAY_LENGTH 24
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMMINVOLUME_ANALOG_OUTPUT 122
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMMINVOLUME_ARRAY_LENGTH 24
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMMAXVOLUME_ANALOG_OUTPUT 146
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMMAXVOLUME_ARRAY_LENGTH 24
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMSTARTVOLUME_ANALOG_OUTPUT 170
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMSTARTVOLUME_ARRAY_LENGTH 24
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCETYPE_ANALOG_OUTPUT 194
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCETYPE_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCEGAIN_ANALOG_OUTPUT 200
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCEGAIN_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCEMODELID_ANALOG_OUTPUT 206
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCEMODELID_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCEPARENTID_ANALOG_OUTPUT 212
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCEPARENTID_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCENETID_ANALOG_OUTPUT 218
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCENETID_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCEENABLED_ANALOG_OUTPUT 224
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCEENABLED_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_SAVEDGROUPSOURCE_ANALOG_OUTPUT 230
#define __S2_AADS_OOTBF_XML_Functions_v1_SAVEDGROUPSOURCE_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_SAVEDGROUPROOMSLOW_ANALOG_OUTPUT 236
#define __S2_AADS_OOTBF_XML_Functions_v1_SAVEDGROUPROOMSLOW_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_SAVEDGROUPROOMSHIGH_ANALOG_OUTPUT 242
#define __S2_AADS_OOTBF_XML_Functions_v1_SAVEDGROUPROOMSHIGH_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_KEYPADMAPOUT_ANALOG_OUTPUT 248
#define __S2_AADS_OOTBF_XML_Functions_v1_KEYPADMAPOUT_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMNAME$_STRING_OUTPUT 254
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMNAME$_ARRAY_LENGTH 24
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCENAME$_STRING_OUTPUT 278
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCENAME$_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_XML_Functions_v1_GROUPNAME$_STRING_OUTPUT 284
#define __S2_AADS_OOTBF_XML_Functions_v1_GROUPNAME$_ARRAY_LENGTH 6

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/
CREATE_INTARRAY1D( S2_AADS_OOTBF_XML_Functions_v1, __SOURCECONTROLENTRYID, 6 );;
CREATE_INTARRAY1D( S2_AADS_OOTBF_XML_Functions_v1, __ROOMOUTPUT, 24 );;
CREATE_INTARRAY1D( S2_AADS_OOTBF_XML_Functions_v1, __ROOMSWITCHER, 24 );;


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_AADS_OOTBF_XML_Functions_v1_ADAGIO_DATA_FILE_STRING_MAX_LEN 64
CREATE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, __ADAGIO_DATA_FILE, __S2_AADS_OOTBF_XML_Functions_v1_ADAGIO_DATA_FILE_STRING_MAX_LEN );
#define __S2_AADS_OOTBF_XML_Functions_v1_CREATEDBY$_STRING_MAX_LEN 64
CREATE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, __CREATEDBY$, __S2_AADS_OOTBF_XML_Functions_v1_CREATEDBY$_STRING_MAX_LEN );
#define __S2_AADS_OOTBF_XML_Functions_v1_INTERFACEBLOCK$_STRING_MAX_LEN 7000
CREATE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, __INTERFACEBLOCK$, __S2_AADS_OOTBF_XML_Functions_v1_INTERFACEBLOCK$_STRING_MAX_LEN );
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMID$_ARRAY_NUM_ELEMS 24
#define __S2_AADS_OOTBF_XML_Functions_v1_ROOMID$_ARRAY_NUM_CHARS 6
CREATE_STRING_ARRAY( S2_AADS_OOTBF_XML_Functions_v1, __ROOMID$, __S2_AADS_OOTBF_XML_Functions_v1_ROOMID$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_XML_Functions_v1_ROOMID$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCEROOMID$_ARRAY_NUM_ELEMS 6
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCEROOMID$_ARRAY_NUM_CHARS 6
CREATE_STRING_ARRAY( S2_AADS_OOTBF_XML_Functions_v1, __SOURCEROOMID$, __S2_AADS_OOTBF_XML_Functions_v1_SOURCEROOMID$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_XML_Functions_v1_SOURCEROOMID$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCECOMMANDFILE$_ARRAY_NUM_ELEMS 6
#define __S2_AADS_OOTBF_XML_Functions_v1_SOURCECOMMANDFILE$_ARRAY_NUM_CHARS 50
CREATE_STRING_ARRAY( S2_AADS_OOTBF_XML_Functions_v1, __SOURCECOMMANDFILE$, __S2_AADS_OOTBF_XML_Functions_v1_SOURCECOMMANDFILE$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_XML_Functions_v1_SOURCECOMMANDFILE$_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_AADS_OOTBF_XML_Functions_v1 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __APADOFFLINE );
   DECLARE_IO_ARRAY( __KEYPADOFFLINE );
   DECLARE_IO_ARRAY( __KEYPADMAPIN );
   DECLARE_IO_ARRAY( __SOURCEENABLEDIN );
   DECLARE_IO_ARRAY( __SLOTID );
   DECLARE_IO_ARRAY( __ROOMBASS );
   DECLARE_IO_ARRAY( __ROOMTREBLE );
   DECLARE_IO_ARRAY( __ROOMBALANCE );
   DECLARE_IO_ARRAY( __ROOMMONO );
   DECLARE_IO_ARRAY( __ROOMLOUDNESS );
   DECLARE_IO_ARRAY( __ROOMMINVOLUME );
   DECLARE_IO_ARRAY( __ROOMMAXVOLUME );
   DECLARE_IO_ARRAY( __ROOMSTARTVOLUME );
   DECLARE_IO_ARRAY( __SOURCETYPE );
   DECLARE_IO_ARRAY( __SOURCEGAIN );
   DECLARE_IO_ARRAY( __SOURCEMODELID );
   DECLARE_IO_ARRAY( __SOURCEPARENTID );
   DECLARE_IO_ARRAY( __SOURCENETID );
   DECLARE_IO_ARRAY( __SOURCEENABLED );
   DECLARE_IO_ARRAY( __SAVEDGROUPSOURCE );
   DECLARE_IO_ARRAY( __SAVEDGROUPROOMSLOW );
   DECLARE_IO_ARRAY( __SAVEDGROUPROOMSHIGH );
   DECLARE_IO_ARRAY( __KEYPADMAPOUT );
   DECLARE_IO_ARRAY( __ROOMNAME$ );
   DECLARE_IO_ARRAY( __SOURCENAME$ );
   DECLARE_IO_ARRAY( __GROUPNAME$ );
   unsigned short __READBUSY;
   unsigned short __WRITEBUSY;
   unsigned short __NEEDWRITE;
   unsigned short __SYSTEMTYPE;
   DECLARE_INTARRAY( S2_AADS_OOTBF_XML_Functions_v1, __SOURCECONTROLENTRYID );
   DECLARE_INTARRAY( S2_AADS_OOTBF_XML_Functions_v1, __ROOMOUTPUT );
   DECLARE_INTARRAY( S2_AADS_OOTBF_XML_Functions_v1, __ROOMSWITCHER );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, __ADAGIO_DATA_FILE );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, __CREATEDBY$ );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, __INTERFACEBLOCK$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_XML_Functions_v1, __ROOMID$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_XML_Functions_v1, __SOURCEROOMID$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_XML_Functions_v1, __SOURCECOMMANDFILE$ );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, __MODELNAME$ );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_XML_Functions_v1, __FILENAME$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_XML_Functions_v1, __INPUTROOMNAME$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_XML_Functions_v1, __INPUTSOURCENAME$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_XML_Functions_v1, __INPUTGROUPNAME$ );
   struct FileInfo_s __G_FIDATAFILE;
};

START_NVRAM_VAR_STRUCT( S2_AADS_OOTBF_XML_Functions_v1 )
{
};



#endif //__S2_AADS_OOTBF_XML_FUNCTIONS_V1_H__

