#ifndef __S2_AADS_OOTBF_GROUP_MODE_V1_H__
#define __S2_AADS_OOTBF_GROUP_MODE_V1_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_AADS_OOTBF_Group_Mode_v1_ENTER_DIG_INPUT 0
#define __S2_AADS_OOTBF_Group_Mode_v1_KNOBLEFT_DIG_INPUT 1
#define __S2_AADS_OOTBF_Group_Mode_v1_KNOBRIGHT_DIG_INPUT 2
#define __S2_AADS_OOTBF_Group_Mode_v1_MENU_DIG_INPUT 3
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUP_DIG_INPUT 4
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPHELD_DIG_INPUT 5

#define __S2_AADS_OOTBF_Group_Mode_v1_SOURCEDISABLED_DIG_INPUT 6
#define __S2_AADS_OOTBF_Group_Mode_v1_SOURCEDISABLED_ARRAY_LENGTH 10
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPACTIVE_DIG_INPUT 16
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPACTIVE_ARRAY_LENGTH 6

/*
* ANALOG_INPUT
*/
#define __S2_AADS_OOTBF_Group_Mode_v1_SOURCESINUSE_ANALOG_INPUT 0

#define __S2_AADS_OOTBF_Group_Mode_v1_TEXTBEINGEDITED$_STRING_INPUT 1
#define __S2_AADS_OOTBF_Group_Mode_v1_TEXTBEINGEDITED$_STRING_MAX_LEN 16
CREATE_STRING_STRUCT( S2_AADS_OOTBF_Group_Mode_v1, __TEXTBEINGEDITED$, __S2_AADS_OOTBF_Group_Mode_v1_TEXTBEINGEDITED$_STRING_MAX_LEN );
#define __S2_AADS_OOTBF_Group_Mode_v1_EDITEDTEXT$_STRING_INPUT 2
#define __S2_AADS_OOTBF_Group_Mode_v1_EDITEDTEXT$_STRING_MAX_LEN 16
CREATE_STRING_STRUCT( S2_AADS_OOTBF_Group_Mode_v1, __EDITEDTEXT$, __S2_AADS_OOTBF_Group_Mode_v1_EDITEDTEXT$_STRING_MAX_LEN );


#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPSOURCEIN_ANALOG_INPUT 3
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPSOURCEIN_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPNAMES$_STRING_INPUT 9
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPNAMES$_ARRAY_NUM_ELEMS 6
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPNAMES$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Group_Mode_v1, __GROUPNAMES$, __S2_AADS_OOTBF_Group_Mode_v1_GROUPNAMES$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Group_Mode_v1_GROUPNAMES$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_Group_Mode_v1_SOURCENAMES$_STRING_INPUT 15
#define __S2_AADS_OOTBF_Group_Mode_v1_SOURCENAMES$_ARRAY_NUM_ELEMS 10
#define __S2_AADS_OOTBF_Group_Mode_v1_SOURCENAMES$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Group_Mode_v1, __SOURCENAMES$, __S2_AADS_OOTBF_Group_Mode_v1_SOURCENAMES$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Group_Mode_v1_SOURCENAMES$_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/
#define __S2_AADS_OOTBF_Group_Mode_v1_EXITGROUPRECALL_DIG_OUTPUT 0
#define __S2_AADS_OOTBF_Group_Mode_v1_EXITGROUPRECALLTOACTIVEMODE_DIG_OUTPUT 1
#define __S2_AADS_OOTBF_Group_Mode_v1_EXITGROUPSETUP_DIG_OUTPUT 2
#define __S2_AADS_OOTBF_Group_Mode_v1_EDITTEXTDONE_DIG_OUTPUT 3

#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPON_DIG_OUTPUT 4
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPON_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPOFF_DIG_OUTPUT 10
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPOFF_ARRAY_LENGTH 6

/*
* ANALOG_OUTPUT
*/
#define __S2_AADS_OOTBF_Group_Mode_v1_CURRENTMENU_ANALOG_OUTPUT 0
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPBEINGEDITED_ANALOG_OUTPUT 1
#define __S2_AADS_OOTBF_Group_Mode_v1_LINE1SCROLLARROW_ANALOG_OUTPUT 2
#define __S2_AADS_OOTBF_Group_Mode_v1_LINE2SCROLLARROW_ANALOG_OUTPUT 3

#define __S2_AADS_OOTBF_Group_Mode_v1_LINE1$_STRING_OUTPUT 4
#define __S2_AADS_OOTBF_Group_Mode_v1_LINE2$_STRING_OUTPUT 5
#define __S2_AADS_OOTBF_Group_Mode_v1_TEXTTOEDIT$_STRING_OUTPUT 6

#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPSOURCEOUT_ANALOG_OUTPUT 7
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPSOURCEOUT_ARRAY_LENGTH 6
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPNAMESOUT$_STRING_OUTPUT 13
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPNAMESOUT$_ARRAY_LENGTH 6

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPEDIT$_ARRAY_NUM_ELEMS 2
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPEDIT$_ARRAY_NUM_CHARS 6
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Group_Mode_v1, __GROUPEDIT$, __S2_AADS_OOTBF_Group_Mode_v1_GROUPEDIT$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Group_Mode_v1_GROUPEDIT$_ARRAY_NUM_CHARS );
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPNAMELIST$_ARRAY_NUM_ELEMS 10
#define __S2_AADS_OOTBF_Group_Mode_v1_GROUPNAMELIST$_ARRAY_NUM_CHARS 16
CREATE_STRING_ARRAY( S2_AADS_OOTBF_Group_Mode_v1, __GROUPNAMELIST$, __S2_AADS_OOTBF_Group_Mode_v1_GROUPNAMELIST$_ARRAY_NUM_ELEMS, __S2_AADS_OOTBF_Group_Mode_v1_GROUPNAMELIST$_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_AADS_OOTBF_Group_Mode_v1 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __SOURCEDISABLED );
   DECLARE_IO_ARRAY( __GROUPACTIVE );
   DECLARE_IO_ARRAY( __GROUPON );
   DECLARE_IO_ARRAY( __GROUPOFF );
   DECLARE_IO_ARRAY( __GROUPSOURCEIN );
   DECLARE_IO_ARRAY( __GROUPSOURCEOUT );
   DECLARE_IO_ARRAY( __GROUPNAMESOUT$ );
   unsigned short __SCROLLINDEX;
   unsigned short __SCROLLMAX;
   unsigned short __OLDSCROLLINDEX;
   unsigned short __CURRENTGROUP;
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Group_Mode_v1, __GROUPEDIT$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Group_Mode_v1, __GROUPNAMELIST$ );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_Group_Mode_v1, __TEXTBEINGEDITED$ );
   DECLARE_STRING_STRUCT( S2_AADS_OOTBF_Group_Mode_v1, __EDITEDTEXT$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Group_Mode_v1, __GROUPNAMES$ );
   DECLARE_STRING_ARRAY( S2_AADS_OOTBF_Group_Mode_v1, __SOURCENAMES$ );
};

START_NVRAM_VAR_STRUCT( S2_AADS_OOTBF_Group_Mode_v1 )
{
};

DEFINE_WAITEVENT( S2_AADS_OOTBF_Group_Mode_v1, GROUPRECALLMESSAGEWAIT );


#endif //__S2_AADS_OOTBF_GROUP_MODE_V1_H__

