#ifndef __S2_XM_GUIDE_ENGINE_H__
#define __S2_XM_GUIDE_ENGINE_H__



/*
* STRUCTURE S2_XM_Guide_Engine__CHANNELDATA
*/
#define CHANNELDATA__S2_XM_Guide_Engine_TITLE$_STRING_MAX_LEN 32
#define CHANNELDATA__S2_XM_Guide_Engine_ARTIST$_STRING_MAX_LEN 32
#define CHANNELDATA__S2_XM_Guide_Engine_SONG$_STRING_MAX_LEN 32
START_STRUCTURE_DEFINITION( S2_XM_Guide_Engine, CHANNELDATA )
{
   CREATE_STRING_STRUCT( S2_XM_Guide_Engine, CHANNELDATA__TITLE$, CHANNELDATA__S2_XM_Guide_Engine_TITLE$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_XM_Guide_Engine, CHANNELDATA__TITLE$ );
   CREATE_STRING_STRUCT( S2_XM_Guide_Engine, CHANNELDATA__ARTIST$, CHANNELDATA__S2_XM_Guide_Engine_ARTIST$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_XM_Guide_Engine, CHANNELDATA__ARTIST$ );
   CREATE_STRING_STRUCT( S2_XM_Guide_Engine, CHANNELDATA__SONG$, CHANNELDATA__S2_XM_Guide_Engine_SONG$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_XM_Guide_Engine, CHANNELDATA__SONG$ );
   unsigned short CHANNELDATA__NUMBER;
   unsigned short CHANNELDATA__MAINCATEGORY;
};

/*
* STRUCTURE S2_XM_Guide_Engine__CATEGORYDATA
*/
#define CATEGORYDATA__S2_XM_Guide_Engine_CATNAME$_STRING_MAX_LEN 32
START_STRUCTURE_DEFINITION( S2_XM_Guide_Engine, CATEGORYDATA )
{
   CREATE_STRING_STRUCT( S2_XM_Guide_Engine, CATEGORYDATA__CATNAME$, CATEGORYDATA__S2_XM_Guide_Engine_CATNAME$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_XM_Guide_Engine, CATEGORYDATA__CATNAME$ );
   unsigned short CATEGORYDATA__CATNUMBER;
};

/*
* STRUCTURE S2_XM_Guide_Engine__CATEGORYSTRUCTURE
*/
START_STRUCTURE_DEFINITION( S2_XM_Guide_Engine, CATEGORYSTRUCTURE )
{
   CREATE_INTARRAY1D( S2_XM_Guide_Engine, CATEGORYSTRUCTURE__TOTAL, 31 );;
   DECLARE_INTARRAY( S2_XM_Guide_Engine, CATEGORYSTRUCTURE__TOTAL );
   CREATE_INTARRAY2D( S2_XM_Guide_Engine, CATEGORYSTRUCTURE__MAP, 31, 255 );;
   DECLARE_INTARRAY( S2_XM_Guide_Engine, CATEGORYSTRUCTURE__MAP );
};


/*
* Constructor and Destructor
*/
int S2_XM_Guide_Engine_CHANNELDATA_Constructor ( START_STRUCTURE_DEFINITION( S2_XM_Guide_Engine, CHANNELDATA ) * me, int nVerbose );
int S2_XM_Guide_Engine_CHANNELDATA_Destructor ( START_STRUCTURE_DEFINITION( S2_XM_Guide_Engine, CHANNELDATA ) * me, int nVerbose );
int S2_XM_Guide_Engine_CATEGORYDATA_Constructor ( START_STRUCTURE_DEFINITION( S2_XM_Guide_Engine, CATEGORYDATA ) * me, int nVerbose );
int S2_XM_Guide_Engine_CATEGORYDATA_Destructor ( START_STRUCTURE_DEFINITION( S2_XM_Guide_Engine, CATEGORYDATA ) * me, int nVerbose );
int S2_XM_Guide_Engine_CATEGORYSTRUCTURE_Constructor ( START_STRUCTURE_DEFINITION( S2_XM_Guide_Engine, CATEGORYSTRUCTURE ) * me, int nVerbose );
int S2_XM_Guide_Engine_CATEGORYSTRUCTURE_Destructor ( START_STRUCTURE_DEFINITION( S2_XM_Guide_Engine, CATEGORYSTRUCTURE ) * me, int nVerbose );

/*
* DIGITAL_INPUT
*/
#define __S2_XM_Guide_Engine_POWERONFB_DIG_INPUT 0
#define __S2_XM_Guide_Engine_POWERINGONFB_DIG_INPUT 1
#define __S2_XM_Guide_Engine_SHOWCATLIST_DIG_INPUT 2
#define __S2_XM_Guide_Engine_SHOWCHANNELLIST_DIG_INPUT 3
#define __S2_XM_Guide_Engine_PRESETSAVEFB_DIG_INPUT 4
#define __S2_XM_Guide_Engine_GENERATEFOCUSLIST_DIG_INPUT 5


/*
* ANALOG_INPUT
*/
#define __S2_XM_Guide_Engine_SHOWCATEGORYCHANNELS_ANALOG_INPUT 0
#define __S2_XM_Guide_Engine_CURRENTCHANNEL_ANALOG_INPUT 3


#define __S2_XM_Guide_Engine_GUIDEINFO$_BUFFER_INPUT 1
#define __S2_XM_Guide_Engine_GUIDEINFO$_BUFFER_MAX_LEN 5000
CREATE_STRING_STRUCT( S2_XM_Guide_Engine, __GUIDEINFO$, __S2_XM_Guide_Engine_GUIDEINFO$_BUFFER_MAX_LEN );
#define __S2_XM_Guide_Engine_GUIDEREQUEST$_BUFFER_INPUT 2
#define __S2_XM_Guide_Engine_GUIDEREQUEST$_BUFFER_MAX_LEN 255
CREATE_STRING_STRUCT( S2_XM_Guide_Engine, __GUIDEREQUEST$, __S2_XM_Guide_Engine_GUIDEREQUEST$_BUFFER_MAX_LEN );

#define __S2_XM_Guide_Engine_PRESETIN_ANALOG_INPUT 4
#define __S2_XM_Guide_Engine_PRESETIN_ARRAY_LENGTH 20

/*
* DIGITAL_OUTPUT
*/
#define __S2_XM_Guide_Engine_PRESETSTOREFB_DIG_OUTPUT 0

#define __S2_XM_Guide_Engine_PRESETFB_DIG_OUTPUT 1
#define __S2_XM_Guide_Engine_PRESETFB_ARRAY_LENGTH 20

/*
* ANALOG_OUTPUT
*/
#define __S2_XM_Guide_Engine_NEWCHANNEL_ANALOG_OUTPUT 0

#define __S2_XM_Guide_Engine_GUIDERESPONSE$_STRING_OUTPUT 1
#define __S2_XM_Guide_Engine_ACTIVATIONNUMBER$_STRING_OUTPUT 2
#define __S2_XM_Guide_Engine_GUIDEERRORMESSAGE_STRING_OUTPUT 3
#define __S2_XM_Guide_Engine_FOCUSLIST$_STRING_OUTPUT 4


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_XM_Guide_Engine_HARDWAREID$_STRING_MAX_LEN 24
CREATE_STRING_STRUCT( S2_XM_Guide_Engine, __HARDWAREID$, __S2_XM_Guide_Engine_HARDWAREID$_STRING_MAX_LEN );

/*
* STRUCTURE
*/
#define __S2_XM_Guide_Engine_CHANNELS_STRUCT_MAX_LEN 255
CREATE_STRUCTURE_ARRAY( S2_XM_Guide_Engine, __CHANNELS, CHANNELDATA, __S2_XM_Guide_Engine_CHANNELS_STRUCT_MAX_LEN );
#define __S2_XM_Guide_Engine_CATEGORIES_STRUCT_MAX_LEN 31
CREATE_STRUCTURE_ARRAY( S2_XM_Guide_Engine, __CATEGORIES, CATEGORYDATA, __S2_XM_Guide_Engine_CATEGORIES_STRUCT_MAX_LEN );

START_GLOBAL_VAR_STRUCT( S2_XM_Guide_Engine )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __PRESETFB );
   DECLARE_IO_ARRAY( __PRESETIN );
   unsigned short __SEMAPHORE;
   unsigned short __SEMAPHORE2;
   unsigned short __LASTCATEGORY;
   unsigned short __LASTCHANNEL;
   unsigned short __TOTALCATEGORIESSTORED;
   unsigned short __TOTALCHANNELSSTORED;
   unsigned short __PRESETTOSAVE;
   unsigned short __REQUESTIDSAVINGPRESET;
   unsigned short __PRESETSAVETYPE;
   unsigned short __ORIGINALCHANNEL;
   DECLARE_STRING_STRUCT( S2_XM_Guide_Engine, __HARDWAREID$ );
   DECLARE_STRING_STRUCT( S2_XM_Guide_Engine, __GUIDEINFO$ );
   DECLARE_STRING_STRUCT( S2_XM_Guide_Engine, __GUIDEREQUEST$ );
   DECLARE_STRUCT( S2_XM_Guide_Engine, CATEGORYSTRUCTURE, __CATEGORYMAP );
   DECLARE_STRUCT_ARRAY( S2_XM_Guide_Engine, __CHANNELS );
   DECLARE_STRUCT_ARRAY( S2_XM_Guide_Engine, __CATEGORIES );
};

START_NVRAM_VAR_STRUCT( S2_XM_Guide_Engine )
{
};



#endif //__S2_XM_GUIDE_ENGINE_H__

